// <auto-generated />
namespace Chavo.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_GeneralConfiguration_VideoCashing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_GeneralConfiguration_VideoCashing));
        
        string IMigrationMetadata.Id
        {
            get { return "202001111921257_Update_GeneralConfiguration_VideoCashing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
